name: Java CI
run-name: ${{ github.actor }} push a new commit to main branch
on: 
  push:
    branches:
      - main
    path-ignore:
      - ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: maven
      - name: Test with Maven
        run: mvn --batch-mode --update-snapshots package