name: Tests
run-name: ${{ github.actor }} push a new commit to main branch
on: 
  push:
    branches:
      - main

env:
  BINANCE_TRADER_ENV: "DEV"
  TESTNET_API_KEY:  ""
  TESTNET_SECRET_KEY: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      - name: Test with Gradle
        run: gradle/gradle-build-action@v2
        with:
          arguments: test